name: Scheduled health check

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  health_check_scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://polished-shape-2590.fly.dev/
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
      - name: Health check Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Piip! Piip! Health check failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
